/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#38485d',
        'surface-bright': '#f7f9fb',
        error: '#ba1a1a',
        'surface-dim': '#d8dadc',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#001b3c',
        'outline-variant': '#c4c6cf',
        'secondary-container': '#d0e1fb',
        'tertiary-fixed-dim': '#4ae176',
        'surface-container-highest': '#e0e3e5',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'on-surface': '#191c1e',
        outline: '#74777f',
        'inverse-primary': '#adc7f7',
        surface: '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#005321',
        'on-tertiary': '#ffffff',
        'surface-container': '#eceef0',
        'on-surface-variant': '#43474e',
        'surface-tint': '#455f88',
        'on-primary-container': '#86a0cd',
        'primary-fixed': '#d6e3ff',
        'on-primary-fixed-variant': '#2d476f',
        'on-tertiary-container': '#00b753',
        tertiary: '#00270c',
        'on-primary': '#ffffff',
        'on-background': '#191c1e',
        'primary-fixed-dim': '#adc7f7',
        'tertiary-container': '#003f18',
        'tertiary-fixed': '#6bff8f',
        'on-error': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'on-secondary-container': '#54647a',
        'surface-container-high': '#e6e8ea',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#d3e4fe',
        primary: '#002045',
        'primary-container': '#1a365d',
        'surface-variant': '#e0e3e5',
        'secondary-fixed-dim': '#b7c8e1',
        'on-tertiary-fixed': '#002109',
        secondary: '#505f76',
        'on-secondary-fixed': '#0b1c30',
        background: '#f7f9fb',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'input-padding': '16px',
        'bubble-gap': '12px',
        unit: '4px',
        'container-padding': '24px',
        'group-gap': '24px',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'chat-bubble': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px) scale(0.97)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        shimmer: {
          '100%': { transform: 'skewX(-12deg) translateX(200%)' },
        },
        pulseScale: {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.3)', opacity: '0.6' },
        },
        typingBounce: {
          '0%, 60%, 100%': { transform: 'translateY(0)' },
          '30%': { transform: 'translateY(-6px)' },
        },
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.4s ease-out forwards',
        shimmer: 'shimmer 2s infinite',
        'pulse-scale': 'pulseScale 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'typing-bounce': 'typingBounce 1.2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
